CREATE DATABASE IF NOT EXISTS AIS_DATA;
USE AIS_DATA;

CREATE TABLE IF NOT EXISTS Vessel_Data(
	ID			INT PRIMARY KEY AUTO_INCREMENT,
	DATE_TIME	VARCHAR(15),
    MMSI		CHAR(9),
    LATITUDE	FLOAT(8, 5),
    LONGITUDE	FLOAT(8, 5),
    COURSE		FLOAT(4, 1),
    SPEED		FLOAT(3, 1),
    HEADING		INT,
    IMO			CHAR(7),
    VESSEL_NAME	VARCHAR(255),
    CALLSIGN	VARCHAR(10),
    AISTYPE		INT,
    A			INT,
    B			INT,
    C			INT,
    D			INT,
    DRAUGHT		FLOAT(3, 1),
    DESTINATION	VARCHAR(255),
    ETA			VARCHAR(15)
);


CREATE TABLE IF NOT EXISTS KML_Data(
	ID			INT PRIMARY KEY AUTO_INCREMENT,
	DATE_TIME	VARCHAR(15),
    LATITUDE	FLOAT(8, 5),
    LONGITUDE	FLOAT(8, 5)
);

CREATE TABLE IF NOT EXISTS stations (
    ID        INT PRIMARY KEY,
    LATITUDE  FLOAT(8, 5),
    LONGITUDE FLOAT(8, 5)
);